# Generated by Django 4.1.1 on 2024-10-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=30)),
                ('image_categorie', models.ImageField(upload_to='img_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='MesProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_produits')),
                ('nom', models.CharField(max_length=30)),
                ('prix', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('date_ajout', models.DateField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.categories')),
            ],
        ),
    ]
