# Generated by Django 4.1.1 on 2024-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesproduits',
            name='description',
            field=models.TextField(),
        ),
    ]
