# Generated by Django 4.1.1 on 2024-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0003_imagescategorie_remove_categories_image_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image_categorie',
        ),
        migrations.DeleteModel(
            name='ImagesCategorie',
        ),
        migrations.AddField(
            model_name='categories',
            name='image_categorie',
            field=models.ImageField(default='mamadou', upload_to='img_categorie'),
            preserve_default=False,
        ),
    ]
