# Generated by Django 4.1.1 on 2024-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0004_remove_categories_image_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesproduits',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
