# Generated by Django 4.1.1 on 2024-10-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0005_mesproduits_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesproduits',
            name='slug',
        ),
    ]
