# Generated by Django 4.1.1 on 2024-10-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0006_remove_mesproduits_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['date_ajout']},
        ),
        migrations.AddField(
            model_name='categories',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
