# Generated by Django 4.1.1 on 2024-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0008_panierorder_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panierorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
