# Generated by Django 4.1.1 on 2024-11-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0010_panier_ordered_alter_panier_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='date',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='ordered',
        ),
        migrations.AddField(
            model_name='panierorder',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
