# Generated by Django 4.1.1 on 2024-11-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0011_remove_panier_date_remove_panier_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
