# Generated by Django 5.1.3 on 2024-11-30 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0013_commander'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commander',
            old_name='addresse',
            new_name='adresse',
        ),
    ]
